In [2]:
#Creating an array
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr = np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [5]:
arr = np.ones(3)
print(arr)

[1. 1. 1.]


In [6]:
arr = np.linspace(0,10,6)
print(arr)

[ 0.  2.  4.  6.  8. 10.]


In [7]:
#This function is used to create an array with random values between 0 and 1.
arr = np.random.rand(4)
print(arr)

[0.00161143 0.09478589 0.42723884 0.21477379]


In [8]:
arr = np.random.randn(4)
print(arr)

[-0.72503566  0.98917965 -0.7322475   1.49403578]


In [9]:
#This function is used to create an array with random integer values between a specified range.
arr = np.random.randint(0,10,5)
print(arr)

[4 6 9 0 2]


In [10]:
arr = np.array([1, 2, 3])
max_value = np.max(arr)
print(max_value)

3


In [11]:
arr = np.array([1, 2, 3])
min_value = np.min(arr)
print(min_value)

1


In [12]:
arr = np.array([1, 2, 3])
mean_value = np.mean(arr)
print(mean_value)

2.0


In [13]:
arr = np.array([1, 2, 3])
median_value = np.median(arr)
print(median_value)

2.0


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print(dot_product)

32


In [23]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[0,0,0]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [26]:
new_arr = arr.reshape(2,6)
print(new_arr)

[[1 2 3 4 5 6]
 [7 8 9 0 0 0]]


In [27]:
arr_shape = arr.shape
print(arr_shape)

(4, 3)


In [28]:
arr = np.random.randint(1,100,15)
print(arr)

[35 56 19 92 69 13 70  4 72 61  4 66  4 64  2]


In [29]:
value = arr.max()
print(value)

92


In [30]:
position = arr.argmax()
print(position)

3


In [31]:
value = arr.min()
print(value)
position = arr.argmin()
print(position)

2
14


In [37]:
def myFunc(a):
    return a**2

arr = [1,2,3,4,5,6,7,8,9,10]
square = list(map(myFunc,arr))
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [39]:
arr = [1,2,3,4,5,6,7,8,9,10]
square = [num**2 for num in arr]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
arr = np.arange(15)
print(arr)
print(arr[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6 7]
