In [1]:
import numpy as np

## seed()

In [2]:
np.random.seed(0)  # seed for reproducibility

## 1-D, 2-D, 3-D

In [16]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print(x3.ndim)
print(x3.shape)

3
(3, 4, 5)


## .ndim .shape .size

In [99]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [100]:
print("dtype:", x3.dtype)

dtype: int32


## .itemsize .nbytes

In [101]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [102]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [112]:
chess = np.zeros((8,8))+1
print(chess)



[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [104]:
np.pi

3.141592653589793

In [105]:
np.linspace(0, np.pi, 3)

array([0.        , 1.57079633, 3.14159265])

In [107]:
sum(np.random.random(10))

6.115998308689614

In [127]:

X = np.random.random((10, 3))

In [129]:
Xmean = X.mean(0)
Xmean

array([0.52241021, 0.49623032, 0.51796963])

In [136]:
x = np.random.randint(1,16,size=(5,3))

In [137]:
np.count_nonzero(x>6)

10

In [142]:
def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
selection_sort(x)

array([1, 2, 3, 4, 5])