# Numpy Excersice

#### Import Numpy as np

In [59]:
import numpy as np

#### Create an array of 10 zeros:

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [61]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives.

In [62]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [63]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all even integers from 10 to 50

In [64]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [65]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use Numpy to generate random numbers between 0 to 1

In [67]:
np.random.rand(1)

array([0.76643707])

#### Use Numpy to generate an array of 25 random numbers sampled fom a standard normal distribution

In [68]:
np.random.randn(25)

array([-0.80266833, -0.49550117, -0.21057264,  0.16329621, -1.76584486,
        2.41501713, -0.57569045,  2.46775884,  0.20909075,  0.89511664,
       -0.44833554, -1.03262063,  0.89061539, -0.42890436, -0.91107743,
        0.21802164,  0.29886174, -1.00883593, -1.68141067, -1.4356089 ,
        0.47503979,  0.67603174, -0.69589648, -1.02785652,  0.40731822])

#### Create the following matrix

In [69]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [70]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [71]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

#### Create a matric of 5x5 with elements ranging from 1 to 25

In [72]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### Create a matrix using indexing

In [73]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [74]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [75]:
arr[3:4,-1:]

array([[20]])

In [76]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [77]:
arr[2:3,-2]

array([14])

In [78]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [79]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in the matrix

In [80]:
arr.sum()

325

#### Get the standard deviation of the values in the matrix

In [81]:
arr.std()

7.211102550927978

#### Get the sum of all the columns in the matrix

In [82]:
arr.sum(axis = 0)

array([55, 60, 65, 70, 75])

#### Get the sum of al the rows in the matrix

In [83]:
arr.sum(axis = 1)

array([ 15,  40,  65,  90, 115])

#### 1. Create 1-D, 2-D and 3-D numpy array

In [84]:
oned = np.array(10)
print(oned)

10


In [85]:
twod = np.arange(10).reshape(5,2)
print(twod)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [86]:
threed = np.arange(1,13).reshape(3,2,2)
print(threed)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


#### 2. Print datatype of an array

In [87]:
print(oned.dtype)
print(twod.dtype)
print(threed.dtype)

int32
int32
int32


#### 3. Print shape and dimensions of all the three different array.

In [88]:
oned.shape

()

In [89]:
oned.ndim

0

In [90]:
twod.shape

(5, 2)

In [91]:
twod.ndim

2

In [92]:
threed.shape

(3, 2, 2)

In [93]:
threed.ndim

3

#### 4. Create a 1-D array of 12 elements filled with zero.

In [94]:
oned = np.zeros(12)
print(oned)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 2-D array elements filled with ones

In [95]:
twod = np.ones(12).reshape(3,4)
print(twod)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 6. Create a 1-D array known as Maths Mark out of 100 having 20 elements

In [96]:
Math_Mark = np.random.randint(0,101,20)
print("Math marks : ",Math_Mark)

Math marks :  [ 79  94 100  53  91  99   2  27  59  38  79  35  13  78  20  15  80  70
  66  26]


#### 7. Sort the above array in ascending and descending order.

In [97]:
asc = np.sort(Math_Mark)
dsc = np.sort(Math_Mark)[::-1]
print("Ascending order : ",asc)
print("Descending order :",dsc)

Ascending order :  [  2  13  15  20  26  27  35  38  53  59  66  70  78  79  79  80  91  94
  99 100]
Descending order : [100  99  94  91  80  79  79  78  70  66  59  53  38  35  27  26  20  15
  13   2]


In [98]:
print("Descending order :",np.flip(asc))

Descending order : [100  99  94  91  80  79  79  78  70  66  59  53  38  35  27  26  20  15
  13   2]


#### 8. Create a copy of sorted array to another variable by deep copying.

#### 9. Create a 2-D array of 5x5 which is an identity matrix and then convert it to 1-D array.

In [99]:
twod = np.eye(5)
oned = twod.flatten()
print("2-D Identity Matrix :")
print(twod)
print("1-D Identity Matrix :",oned)

2-D Identity Matrix :
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
1-D Identity Matrix : [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]


In [100]:
print("1-D Identity Matrix :",twod.ravel())

1-D Identity Matrix : [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.]


#### 10. Create 2-D array of 3x3. Add one more row to it.

In [101]:
twod = np.arange(9).reshape(3,3)
new_twod = np.append(twod,[[56,66,76]],axis=0)
print(new_twod)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [56 66 76]]


In [102]:
oned = np.array([22,54,67])
np.vstack((twod,oned))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [22, 54, 67]])

#### 11. Split the above array created vertically and horizontally.

In [103]:
np.vsplit(new_twod,4)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[56, 66, 76]])]

In [104]:
np.hsplit(new_twod,3)

[array([[ 0],
        [ 3],
        [ 6],
        [56]]),
 array([[ 1],
        [ 4],
        [ 7],
        [66]]),
 array([[ 2],
        [ 5],
        [ 8],
        [76]])]

#### 12. Create 4x4 identity matrix. Add 4 to each element.

In [105]:
print((np.eye(4))+4)

[[5. 4. 4. 4.]
 [4. 5. 4. 4.]
 [4. 4. 5. 4.]
 [4. 4. 4. 5.]]


#### 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and round (with 2 decimal's).

In [106]:
oned = np.random.uniform(1,5,5)
print(oned)
print(np.ceil(oned))
print(np.floor(oned))
print(np.round(oned, decimals=2))

[3.31902469 1.79416141 4.58071294 2.58488779 4.09132274]
[4. 2. 5. 3. 5.]
[3. 1. 4. 2. 4.]
[3.32 1.79 4.58 2.58 4.09]


#### 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.

In [107]:
mat = np.random.randint(1,100,(5,5))
print(mat)
print("Column-wise statistics.")
print("Minimum Values :",np.min(mat, axis=0))
print("Maximum Values :",np.max(mat, axis=0))
print("Variance :",np.var(mat, axis=0))
print("Standard Deviation :",np.std(mat, axis=0))

[[46 84 46 31 43]
 [42 77  8 65  8]
 [ 1 31 45 49 57]
 [49 29 96 43 52]
 [37  8 23 10 48]]
Column-wise statistics.
Minimum Values : [ 1  8  8 10  8]
Maximum Values : [49 84 96 65 57]
Variance : [305.2  872.56 889.04 339.04 303.44]
Standard Deviation : [17.46997424 29.5391266  29.8167738  18.41303886 17.41952927]


#### 15. Create a null vector of size 10 with 6 th value filled with 200.

In [108]:
null_vector = np.empty(10)
null_vector[0:] = 'NaN'
null_vector[5] = 200
print(null_vector)

[ nan  nan  nan  nan  nan 200.  nan  nan  nan  nan]


#### 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.

In [109]:
print(np.arange(100,151))

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150]


#### 17. Reverse the above vector.

In [110]:
arr = np.arange(100,151)
print(arr[::-1])

[150 149 148 147 146 145 144 143 142 141 140 139 138 137 136 135 134 133
 132 131 130 129 128 127 126 125 124 123 122 121 120 119 118 117 116 115
 114 113 112 111 110 109 108 107 106 105 104 103 102 101 100]


#### 18. Create a 5x5 matrix with values ranging from 0-24 using some function.

In [117]:
def matrix(start,end,size):
    return np.linspace(start,end,size,dtype=int)
mat = matrix(0,24,25).reshape(5,5)
print(mat)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 19. Find indices of non-zero elements from [1,0,2,0,0,4,0,8]

In [111]:
arr = [1,0,2,0,0,4,0,8]
print(np.nonzero(arr))

(array([0, 2, 5, 7], dtype=int64),)


#### 20. Create a 10x10 matrix with 1 on the borders and 0 inside.

In [124]:
# Changing the borders
matrix = np.zeros((10,10))
matrix[0,:] = 1
matrix[-1,:] = 1
matrix[:,0] = 1
matrix[:,-1] = 1
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [125]:
# Changing the inside of the border.
matrix = np.ones((10,10))
matrix[1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 21. Create 8x8 matrix and fill with 1 and 0 in chessboard pattern.

In [134]:
matrix = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i, j] = 1
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [120]:
def chess(shape):
    return np.indices(shape).sum(axis=0) % 2
chess((8,8))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

#### 22. Create two 3x3 matrix with random integer values. Perform matrix addition, multiplication and subtraction.

In [137]:
mat_1 = np.random.randint(1,100,(3,3))
mat_2 = np.random.randint(1,100,(3,3))
print("Matrix A is :\n",mat_1)
print("Matrix B is :\n",mat_2)
print("The sum of the matrix A and B is :\n",(mat_1+mat_2))
print("The difference between matrix A and B is :\n",(mat_1-mat_2))
print("The difference between matrix B and A is :\n",(mat_2-mat_1))
print("The product of matrix A and B is :\n",(np.dot(mat_1,mat_2)))
print("The product of matrix A and B is :\n",(mat_1@mat_2))

Matrix A is :
 [[37  8 41]
 [55 67 74]
 [10 95 67]]
Matrix B is :
 [[42 10 32]
 [38 16 33]
 [27 89 92]]
The sum of the matrix A and B is :
 [[ 79  18  73]
 [ 93  83 107]
 [ 37 184 159]]
The difference between matrix A and B is :
 [[ -5  -2   9]
 [ 17  51  41]
 [-17   6 -25]]
The difference between matrix B and A is :
 [[  5   2  -9]
 [-17 -51 -41]
 [ 17  -6  25]]
The product of matrix A and B is :
 [[ 2965  4147  5220]
 [ 6854  8208 10779]
 [ 5839  7583  9619]]
The product of matrix A and B is :
 [[ 2965  4147  5220]
 [ 6854  8208 10779]
 [ 5839  7583  9619]]


### Question: Use where()

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
new_arr = np.where(arr % 2 == 0, arr, -1)
print(new_arr)
new_arr1 = np.where(arr % 2 == 1, arr, 78)
print(new_arr1)